server:
  port: 8443

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/question_answer?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

