server:
  port: 8443

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/question_answer?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2609231098@qq.com
    password: pkzkwytustijeace
#application.yml格式
uploadFile:
  path: D://icon/   #(注意了后面一定加“\”)
  staticAccessPath: /D://icon/**
